#!/usr/bin/env python3
"""
Generate actionable manifests for LD construction and region tiling based on gap reports.

This consumes:
  - results/fine_mapping/ld_gaps.tsv
  - results/fine_mapping/variant_overflow.tsv
  - config/regions_curated.csv
  - data_processed/ld_reference/variants/*.tsv
"""

from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple
from collections import defaultdict

import yaml


def to_safe(name: str) -> str:
    return name.replace("/", "_").replace(".", "_")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--ld-gaps",
        default="results/fine_mapping/ld_gaps.tsv",
        help="LD gap TSV generated by fine_mapping_gap_reports.py.",
    )
    p.add_argument(
        "--overflow",
        default="results/fine_mapping/variant_overflow.tsv",
        help="Variant overflow TSV generated by fine_mapping_gap_reports.py.",
    )
    p.add_argument(
        "--regions",
        default="config/regions_curated.csv",
        help="Curated region definitions with chr/start/end.",
    )
    p.add_argument(
        "--variant-dir",
        default="data_processed/ld_reference/variants",
        help="Directory containing per-region variant lists.",
    )
    p.add_argument(
        "--config",
        default="config/config.yaml",
        help="Config YAML (for ancestry list).",
    )
    p.add_argument(
        "--susie-max-variants",
        type=int,
        default=6000,
        help="Variant limit per SuSiE job; used to estimate tiling.",
    )
    p.add_argument(
        "--ld-plan-out",
        default="results/fine_mapping/ld_build_plan.tsv",
        help="Output TSV describing LD build requirements per region×ancestry.",
    )
    p.add_argument(
        "--split-plan-out",
        default="results/fine_mapping/variant_split_plan.tsv",
        help="Output TSV describing recommended region tiling.",
    )
    return p.parse_args()


def read_regions(path: Path) -> Tuple[Dict[str, Dict[str, str]], Dict[str, List[str]]]:
    regions: Dict[str, Dict[str, str]] = {}
    parent_map: Dict[str, List[str]] = defaultdict(list)
    with path.open() as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            region_id = row.get("region_id")
            if not region_id:
                continue
            safe_id = to_safe(region_id)
            parent_region = row.get("parent_region") or region_id
            regions[region_id] = {
                "chr": row.get("chr", ""),
                "start": row.get("start", ""),
                "end": row.get("end", ""),
                "region_safe": safe_id,
                "parent_region": parent_region,
            }
            parent_map[parent_region].append(region_id)
    return regions, parent_map


def read_variant_counts(variant_dir: Path) -> Dict[str, int]:
    counts: Dict[str, int] = {}
    if not variant_dir.exists():
        return counts
    for path in variant_dir.glob("*.tsv"):
        try:
            with path.open() as handle:
                next(handle, None)
                count = sum(1 for _ in handle)
        except OSError:
            continue
        counts[path.stem] = count
    return counts


def _read_tsv(path: Path) -> List[Dict[str, str]]:
    if not path.exists():
        return []
    with path.open() as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        return list(reader)


def _to_int(value: Optional[str]) -> Optional[int]:
    if value is None:
        return None
    value = value.strip()
    if not value:
        return None
    try:
        return int(value)
    except ValueError:
        try:
            return int(float(value))
        except ValueError:
            return None


def main() -> None:
    args = parse_args()
    region_meta, parent_map = read_regions(Path(args.regions))
    def infer_ancestries(cfg: Dict) -> List[str]:
        ancestries = set(cfg.get("ancestries", []))
        trait_map = cfg.get("trait_ancestries", {})
        if isinstance(trait_map, dict):
            for values in trait_map.values():
                if isinstance(values, list):
                    ancestries.update(values)
        return sorted(a for a in ancestries if a)

    try:
        cfg = yaml.safe_load(Path(args.config).read_text())
        ancestries = infer_ancestries(cfg or {})
    except FileNotFoundError:
        ancestries = []
    variant_counts = read_variant_counts(Path(args.variant_dir))
    ld_gap_rows = _read_tsv(Path(args.ld_gaps))
    overflow_rows = _read_tsv(Path(args.overflow))

    ld_plan: Dict[Tuple[str, str], Dict[str, str]] = {}

    def target_regions(region_id: str) -> List[str]:
        if region_id in region_meta:
            return [region_id]
        children = parent_map.get(region_id, [])
        if children:
            return children
        return [region_id]

    for row in ld_gap_rows:
        ancestry = row.get("ancestry", "")
        for rid in target_regions(row.get("region_id", "")):
            key = (ancestry, rid)
            entry = ld_plan.setdefault(
                key,
                {
                    "ancestry": ancestry,
                    "region_id": rid,
                    "chr": "",
                    "start": "",
                    "end": "",
                    "variant_total": "",
                    "traits": set(),
                    "statuses": set(),
                    "ld_flag": row.get("ld_flag", ""),
                    "ld_status_raw": row.get("ld_status_raw", ""),
                    "ld_matrix_path": row.get("ld_matrix_path", ""),
                },
            )
            entry["traits"].add(row.get("trait", ""))
            entry["statuses"].add(row.get("status", ""))
            coords = region_meta.get(rid, {})
            entry["chr"] = coords.get("chr", entry["chr"])
            entry["start"] = coords.get("start", entry["start"])
            entry["end"] = coords.get("end", entry["end"])
            vc = variant_counts.get(rid) or variant_counts.get(coords.get("region_safe", ""))
            entry["variant_total"] = str(vc) if vc is not None else entry["variant_total"]

    for ancestry in ancestries or []:
        for region_id, meta in region_meta.items():
            key = (ancestry, region_id)
            if key in ld_plan:
                continue
            vc = variant_counts.get(region_id) or variant_counts.get(meta["region_safe"])
            ld_plan[key] = {
                "ancestry": ancestry,
                "region_id": region_id,
                "chr": meta.get("chr", ""),
                "start": meta.get("start", ""),
                "end": meta.get("end", ""),
                "variant_total": str(vc) if vc is not None else "",
                "traits": set(),
                "statuses": set(),
                "ld_flag": "ld_missing",
                "ld_status_raw": "",
                "ld_matrix_path": "",
            }
    ld_plan_rows: List[Dict[str, str]] = []
    for entry in ld_plan.values():
        traits = sorted(t for t in entry["traits"] if t)
        statuses = sorted(s for s in entry["statuses"] if s)
        region_id = entry["region_id"]
        ancestry = entry["ancestry"]
        region_safe = to_safe(region_id)
        ld_rds_path = (
            f"data_processed/ld_reference/{ancestry}/{region_safe}.rds"
            if ancestry and region_id
            else ""
        )
        ld_plan_rows.append(
            {
                "ancestry": ancestry,
                "region_id": region_id,
                "region_safe": region_safe,
                "chr": entry.get("chr", ""),
                "start": entry.get("start", ""),
                "end": entry.get("end", ""),
                "variant_total": entry.get("variant_total", ""),
                "traits": ",".join(traits),
                "statuses": ",".join(statuses),
                "ld_flag": entry.get("ld_flag", ""),
                "ld_status_raw": entry.get("ld_status_raw", ""),
                "ld_matrix_path": entry.get("ld_matrix_path", ""),
                "ld_rds_expected": ld_rds_path,
                "samples_file": f"data_raw/1kg/{ancestry}.samples" if ancestry else "",
            }
        )

    split_plan_rows: List[Dict[str, str]] = []
    seen_split: Dict[Tuple[str, str], Dict[str, str]] = {}

    def record_split(ancestry: str, region: str, status: str, total_variants: Optional[int], tile_size: str, tile_count: str):
        seen_split[(ancestry, region)] = {
            "ancestry": ancestry,
            "region_id": region,
            "region_safe": to_safe(region),
            "chr": region_meta.get(region, {}).get("chr", ""),
            "start": region_meta.get(region, {}).get("start", ""),
            "end": region_meta.get(region, {}).get("end", ""),
            "variant_total": str(total_variants) if total_variants is not None else "",
            "status": status,
            "susie_max_variants": args.susie_max_variants,
            "recommended_tiles": tile_count,
            "tile_size_bp": tile_size,
        }

    for row in overflow_rows:
        region = row.get("region_id", "")
        ancestry = row.get("ancestry", "")
        for rid in target_regions(region):
            coords = region_meta.get(rid, {})
            total = variant_counts.get(rid) or variant_counts.get(coords.get("region_safe", ""))
            fallback_total = _to_int(row.get("region_variant_total"))
            total_variants = total if total is not None else fallback_total
            start = _to_int(coords.get("start"))
            end = _to_int(coords.get("end"))
            width = (end - start) if (start is not None and end is not None) else None
            if total_variants is None:
                tile_count = ""
                tile_size = ""
            else:
                tiles = max(1, math.ceil(total_variants / args.susie_max_variants))
                tile_count = str(tiles)
                tile_size = str(math.ceil(width / tiles)) if width is not None else ""
            record_split(ancestry, rid, row.get("status", ""), total_variants, tile_size, tile_count)

    for ancestry in ancestries or []:
        for region_id, meta in region_meta.items():
            key = (ancestry, region_id)
            if key in seen_split:
                continue
            total = variant_counts.get(region_id) or variant_counts.get(meta["region_safe"])
            if total is None:
                tile_count = ""
                tile_size = ""
            else:
                tiles = max(1, math.ceil(total / args.susie_max_variants))
                tile_count = str(tiles)
                width = int(float(meta.get("end"))) - int(float(meta.get("start")))
                tile_size = str(math.ceil(width / tiles)) if width > 0 else ""
            record_split(ancestry, region_id, "auto", total, tile_size, tile_count)

    split_plan_rows = list(seen_split.values())

    ld_plan_path = Path(args.ld_plan_out)
    ld_plan_path.parent.mkdir(parents=True, exist_ok=True)
    if ld_plan_rows:
        headers = list(ld_plan_rows[0].keys())
    else:
        headers = [
            "ancestry",
            "region_id",
            "chr",
            "start",
            "end",
            "variant_total",
            "traits",
            "statuses",
            "ld_flag",
            "ld_status_raw",
            "ld_matrix_path",
            "ld_rds_expected",
            "samples_file",
        ]
    with ld_plan_path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=headers, delimiter="\t")
        writer.writeheader()
        writer.writerows(ld_plan_rows)

    split_plan_path = Path(args.split_plan_out)
    split_plan_path.parent.mkdir(parents=True, exist_ok=True)
    if split_plan_rows:
        split_headers = list(split_plan_rows[0].keys())
    else:
        split_headers = [
            "ancestry",
            "region_id",
            "chr",
            "start",
            "end",
            "variant_total",
            "status",
            "susie_max_variants",
            "recommended_tiles",
            "tile_size_bp",
        ]
    with split_plan_path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=split_headers, delimiter="\t")
        writer.writeheader()
        writer.writerows(split_plan_rows)


if __name__ == "__main__":
    main()
