#!/usr/bin/env bash
set -e
python3 scripts/build_ld_rds.py --vcf data_raw/1kg/vcf/chr22.vcf.gz --samples data_raw/1kg/TRANS.samples --chrom 22 --start 36422406 --end 36599948 --region-id APOL1_22q12__tile2 --ancestry TRANS --output data_processed/ld_reference/TRANS/APOL1_22q12__tile2.rds --rscript /share/clintonlab/ckclinto/admix_map/.conda/admix_map_r/bin/Rscript --variant-list data_processed/ld_reference/variants/APOL1_22q12__tile2.tsv
python3 scripts/build_ld_rds.py --vcf data_raw/1kg/vcf/chr1.vcf.gz --samples data_raw/1kg/TRANS.samples --chrom 1 --start 158000013 --end 158307459 --region-id PYHIN1_1q23__tile1 --ancestry TRANS --output data_processed/ld_reference/TRANS/PYHIN1_1q23__tile1.rds --rscript /share/clintonlab/ckclinto/admix_map/.conda/admix_map_r/bin/Rscript --variant-list data_processed/ld_reference/variants/PYHIN1_1q23__tile1.tsv
python3 scripts/build_ld_rds.py --vcf data_raw/1kg/vcf/chr1.vcf.gz --samples data_raw/1kg/TRANS.samples --chrom 1 --start 158307478 --end 158571445 --region-id PYHIN1_1q23__tile2 --ancestry TRANS --output data_processed/ld_reference/TRANS/PYHIN1_1q23__tile2.rds --rscript /share/clintonlab/ckclinto/admix_map/.conda/admix_map_r/bin/Rscript --variant-list data_processed/ld_reference/variants/PYHIN1_1q23__tile2.tsv
python3 scripts/build_ld_rds.py --vcf data_raw/1kg/vcf/chr1.vcf.gz --samples data_raw/1kg/TRANS.samples --chrom 1 --start 158571480 --end 158867799 --region-id PYHIN1_1q23__tile3 --ancestry TRANS --output data_processed/ld_reference/TRANS/PYHIN1_1q23__tile3.rds --rscript /share/clintonlab/ckclinto/admix_map/.conda/admix_map_r/bin/Rscript --variant-list data_processed/ld_reference/variants/PYHIN1_1q23__tile3.tsv
python3 scripts/build_ld_rds.py --vcf data_raw/1kg/vcf/chr1.vcf.gz --samples data_raw/1kg/TRANS.samples --chrom 1 --start 158867800 --end 159208911 --region-id PYHIN1_1q23__tile4 --ancestry TRANS --output data_processed/ld_reference/TRANS/PYHIN1_1q23__tile4.rds --rscript /share/clintonlab/ckclinto/admix_map/.conda/admix_map_r/bin/Rscript --variant-list data_processed/ld_reference/variants/PYHIN1_1q23__tile4.tsv
python3 scripts/build_ld_rds.py --vcf data_raw/1kg/vcf/chr1.vcf.gz --samples data_raw/1kg/TRANS.samples --chrom 1 --start 159209082 --end 159546980 --region-id PYHIN1_1q23__tile5 --ancestry TRANS --output data_processed/ld_reference/TRANS/PYHIN1_1q23__tile5.rds --rscript /share/clintonlab/ckclinto/admix_map/.conda/admix_map_r/bin/Rscript --variant-list data_processed/ld_reference/variants/PYHIN1_1q23__tile5.tsv
python3 scripts/build_ld_rds.py --vcf data_raw/1kg/vcf/chr1.vcf.gz --samples data_raw/1kg/TRANS.samples --chrom 1 --start 159547055 --end 159892079 --region-id PYHIN1_1q23__tile6 --ancestry TRANS --output data_processed/ld_reference/TRANS/PYHIN1_1q23__tile6.rds --rscript /share/clintonlab/ckclinto/admix_map/.conda/admix_map_r/bin/Rscript --variant-list data_processed/ld_reference/variants/PYHIN1_1q23__tile6.tsv
python3 scripts/build_ld_rds.py --vcf data_raw/1kg/vcf/chr1.vcf.gz --samples data_raw/1kg/TRANS.samples --chrom 1 --start 159892088 --end 160245171 --region-id PYHIN1_1q23__tile7 --ancestry TRANS --output data_processed/ld_reference/TRANS/PYHIN1_1q23__tile7.rds --rscript /share/clintonlab/ckclinto/admix_map/.conda/admix_map_r/bin/Rscript --variant-list data_processed/ld_reference/variants/PYHIN1_1q23__tile7.tsv
python3 scripts/build_ld_rds.py --vcf data_raw/1kg/vcf/chr1.vcf.gz --samples data_raw/1kg/TRANS.samples --chrom 1 --start 160245226 --end 160585122 --region-id PYHIN1_1q23__tile8 --ancestry TRANS --output data_processed/ld_reference/TRANS/PYHIN1_1q23__tile8.rds --rscript /share/clintonlab/ckclinto/admix_map/.conda/admix_map_r/bin/Rscript --variant-list data_processed/ld_reference/variants/PYHIN1_1q23__tile8.tsv
python3 scripts/build_ld_rds.py --vcf data_raw/1kg/vcf/chr1.vcf.gz --samples data_raw/1kg/TRANS.samples --chrom 1 --start 160585174 --end 160896380 --region-id PYHIN1_1q23__tile9 --ancestry TRANS --output data_processed/ld_reference/TRANS/PYHIN1_1q23__tile9.rds --rscript /share/clintonlab/ckclinto/admix_map/.conda/admix_map_r/bin/Rscript --variant-list data_processed/ld_reference/variants/PYHIN1_1q23__tile9.tsv
python3 scripts/build_ld_rds.py --vcf data_raw/1kg/vcf/chr1.vcf.gz --samples data_raw/1kg/TRANS.samples --chrom 1 --start 160896510 --end 161266180 --region-id PYHIN1_1q23__tile10 --ancestry TRANS --output data_processed/ld_reference/TRANS/PYHIN1_1q23__tile10.rds --rscript /share/clintonlab/ckclinto/admix_map/.conda/admix_map_r/bin/Rscript --variant-list data_processed/ld_reference/variants/PYHIN1_1q23__tile10.tsv
python3 scripts/build_ld_rds.py --vcf data_raw/1kg/vcf/chr1.vcf.gz --samples data_raw/1kg/TRANS.samples --chrom 1 --start 161266192 --end 161631002 --region-id PYHIN1_1q23__tile11 --ancestry TRANS --output data_processed/ld_reference/TRANS/PYHIN1_1q23__tile11.rds --rscript /share/clintonlab/ckclinto/admix_map/.conda/admix_map_r/bin/Rscript --variant-list data_processed/ld_reference/variants/PYHIN1_1q23__tile11.tsv
python3 scripts/build_ld_rds.py --vcf data_raw/1kg/vcf/chr1.vcf.gz --samples data_raw/1kg/TRANS.samples --chrom 1 --start 161631042 --end 161999883 --region-id PYHIN1_1q23__tile12 --ancestry TRANS --output data_processed/ld_reference/TRANS/PYHIN1_1q23__tile12.rds --rscript /share/clintonlab/ckclinto/admix_map/.conda/admix_map_r/bin/Rscript --variant-list data_processed/ld_reference/variants/PYHIN1_1q23__tile12.tsv
python3 scripts/build_ld_rds.py --vcf data_raw/1kg/vcf/chr6.vcf.gz --samples data_raw/1kg/TRANS.samples --chrom 6 --start 10300006 --end 10573038 --region-id CXADR_F2RL1_6p21__tile1 --ancestry TRANS --output data_processed/ld_reference/TRANS/CXADR_F2RL1_6p21__tile1.rds --rscript /share/clintonlab/ckclinto/admix_map/.conda/admix_map_r/bin/Rscript --variant-list data_processed/ld_reference/variants/CXADR_F2RL1_6p21__tile1.tsv
python3 scripts/build_ld_rds.py --vcf data_raw/1kg/vcf/chr6.vcf.gz --samples data_raw/1kg/TRANS.samples --chrom 6 --start 10573168 --end 10905090 --region-id CXADR_F2RL1_6p21__tile2 --ancestry TRANS --output data_processed/ld_reference/TRANS/CXADR_F2RL1_6p21__tile2.rds --rscript /share/clintonlab/ckclinto/admix_map/.conda/admix_map_r/bin/Rscript --variant-list data_processed/ld_reference/variants/CXADR_F2RL1_6p21__tile2.tsv
python3 scripts/build_ld_rds.py --vcf data_raw/1kg/vcf/chr6.vcf.gz --samples data_raw/1kg/TRANS.samples --chrom 6 --start 10905260 --end 11216279 --region-id CXADR_F2RL1_6p21__tile3 --ancestry TRANS --output data_processed/ld_reference/TRANS/CXADR_F2RL1_6p21__tile3.rds --rscript /share/clintonlab/ckclinto/admix_map/.conda/admix_map_r/bin/Rscript --variant-list data_processed/ld_reference/variants/CXADR_F2RL1_6p21__tile3.tsv
python3 scripts/build_ld_rds.py --vcf data_raw/1kg/vcf/chr6.vcf.gz --samples data_raw/1kg/TRANS.samples --chrom 6 --start 11216315 --end 11500417 --region-id CXADR_F2RL1_6p21__tile4 --ancestry TRANS --output data_processed/ld_reference/TRANS/CXADR_F2RL1_6p21__tile4.rds --rscript /share/clintonlab/ckclinto/admix_map/.conda/admix_map_r/bin/Rscript --variant-list data_processed/ld_reference/variants/CXADR_F2RL1_6p21__tile4.tsv
python3 scripts/build_ld_rds.py --vcf data_raw/1kg/vcf/chr6.vcf.gz --samples data_raw/1kg/TRANS.samples --chrom 6 --start 11500431 --end 11799993 --region-id CXADR_F2RL1_6p21__tile5 --ancestry TRANS --output data_processed/ld_reference/TRANS/CXADR_F2RL1_6p21__tile5.rds --rscript /share/clintonlab/ckclinto/admix_map/.conda/admix_map_r/bin/Rscript --variant-list data_processed/ld_reference/variants/CXADR_F2RL1_6p21__tile5.tsv
